spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=TodoApp;username=sa;password=test1234@
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  application:
    name: todo-app
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: DEBUG
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub
