module-name: TodoApp
api-version: v1
spring:
  datasource:
    url: jdbc:sqlite:TodoApp.db
    driverClassName: org.sqlite.JDBC
    username: sa
    password: sa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect        
    hibernate:
      ddl-auto: update
  application:
    name: todo-app
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: DEBUG

security:
  jwt:
   key:
    private: classpath:app.key
    public: classpath:app.pub
   expiration: 3600000 #1h
